function [fitresult, gof] = create2poly(line1x, line1y)
%CREATEFIT(LINE1X,LINE1Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : line1x
%      Y Output: line1y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Nov-2016 21:10:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( line1x, line1y );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



