function [fitresult, gof] = createLineInv(line1y, line1x, dim)
%CREATEFIT(LINE1Y,LINE1X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : line1y
%      Y Output: line1x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Nov-2016 20:27:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( line1y, line1x );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, ~] = fit( xData, yData, ft );
coeffs = coeffvalues(fitresult);
image = false(dim);
x = 1:0.1:dim(1);
y = floor(polyval(coeffs,x));
x = floor(x);
x(y<1 | y>dim(2)) = [];
y(y<1 | y>dim(2)) = [];
for j = 1:size(x,2)
    image(x(j),y(j)) = 1;
end
[liney,linex] = ind2sub(dim,find(image==1));
[fitresult, gof] = createLine(linex,liney);


