function chess = objChess()
    chess = struct(...    
    'center_x', 0, ...
    'center_y', 0,...
    'intersections_x',0,...
    'intersections_y',0,...
    'centroid',0,...
    'background','',...
    'mask',0,...
    'ch_mask',0,...
    'position','',...
    'type','',...
    'h_lines','',...
    'v_lines','',...
    'v_lines_centroid',0);
end

