function [fitresult, gof] = createLine(idy, idx)
%CREATEFIT6(IDY,IDX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : idy
%      Y Output: idx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Oct-2016 16:36:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( idy, idx );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'idx vs. idy', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel idy
% ylabel idx
% grid on


