function obj = objBlobs(name)
    obj = struct(...
        'name',name,...
        'chess',objChess(),...
        'bbox_x',0,...
        'bbox_y',0,...
        'color_mask',0,...
        'inv_color_mask',0,...
        'black_white',0,...
        'masked_rgb',0,...
        'raw_bw',0,...
        'raw_maskedRGBImage',0,...
        'isEmpty',true);   
end