function [fitresult, gof] = createFit(idx, idy)
%CREATEFIT(IDX,IDY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : idx
%      Y Output: idy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Oct-2016 23:48:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( idx, idy );

% Set up fittype and options.
ft = fittype( 'a*x+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.957506835434298 0.964888535199277];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'idy vs. idx', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel idx
% ylabel idy
% grid on


