function chess = objChess()
    chess = struct(...    
    'center_x', 0, ...
    'center_y', 0,...
    'centroid',0,...
    'background','',...
    'left_color','',...
    'right_color','',...
    'mask',0,...
    'ch_mask',0,...
    'position','',...
    'type','');
end

