function obj = objBlobs(name)
    obj = struct(...
        'name',name,...
        'chess',objChess(),...
        'bbox_x',0,...
        'bbox_y',0,...
        'color_mask',0,...
        'inv_color_mask',0,...
        'black_white',0);   
end